export const products = [
  {
    id: 7, name: 'HP 250 G5 Notebook', category: 'Laptops',
    slug: 'hp-250-g5',
    processor: 'Core i5 6th Gen', storage: '256GB SSD',
    display: '15" HD', price: 200, originalPrice: null,
    badge: 'DEAL', inStock: true, rating: 4.3, reviews: 3,
    image: '/images/hp-250-g5.jpg',
    description: 'Reliable HP 250 G5 notebook powered by Intel Core i5 6th generation. Perfect for everyday productivity, with 8GB RAM and a fast 256GB SSD.',
    features: ['Core i5 6th Generation', '8GB RAM', '256GB SSD', 'Windows 11 Pro', '15" HD Display', 'Lightweight design'],
  },

  // ─── GAMING DESKTOPS ───
  {
    id: 8, name: 'Gaming Desktop', category: 'Gaming',
    slug: 'gaming-desktop',
    processor: 'Core i7 10th Gen', storage: '512GB SSD + 16GB RAM',
    display: 'N/A', price: 1250, originalPrice: null,
    badge: 'GAMING', inStock: true, rating: 4.7, reviews: 6,
    image: '/images/gaming-desktop.jpg',
    description: 'High-performance gaming desktop with Core i7 10th Gen, 16GB RAM, 512GB SSD, and a dedicated AMD Radeon RX 5 8GB graphics card. Features 4 RGB cooling fans and USB-C port.',
    features: ['Core i7 10th Generation', '16GB RAM', '512GB SSD', '8GB Dedicated GPU (AMD Radeon RX 5)', '4 RGB Cooling Fans', 'USB-C Port', 'Windows 11 Pro'],
  },
  {
    id: 19, name: 'Gaming Desktop Core i9', category: 'Gaming',
    slug: 'gaming-desktop-i9',
    processor: 'Core i9 11th Gen', storage: '512GB SSD',
    display: 'N/A', price: 1000, originalPrice: null,
    badge: 'GAMING', inStock: true, rating: 4.8, reviews: 4,
    image: '/images/gaming-desktop-i9.jpg',
    description: 'Ultimate gaming desktop powered by Intel Core i9 11th Generation processor. Blazing fast performance for the most demanding games and applications.',
    features: ['Core i9 11th Generation', 'High-performance cooling', 'Dedicated graphics', 'Custom RGB lighting', 'Windows 11 Pro'],
  },

  // ─── GAMING CONSOLES ───
  {
    id: 20, name: 'PlayStation 5 & Slim', category: 'Gaming',
    slug: 'playstation-5',
    processor: 'Custom AMD Zen 2', storage: '825GB / 1TB SSD',
    display: '4K / 120Hz', price: 550, originalPrice: null,
    badge: 'CONSOLE', inStock: true, rating: 4.9, reviews: 15,
    image: '/images/playstation-5.jpg',
    description: 'PlayStation 5 ordinary $550. PlayStation 5 Slim $630. Next-gen gaming with lightning-fast loading, haptic feedback, and stunning 4K graphics.',
    features: ['PS5 Standard $550', 'PS5 Slim $630', 'Custom SSD storage', '4K / 120Hz output', 'DualSense controller', 'Ray tracing support'],
  },
  {
    id: 21, name: 'Xbox Series X', category: 'Gaming',
    slug: 'xbox-series-x',
    processor: 'Custom AMD Zen 2', storage: '1TB SSD',
    display: '4K / 120Hz', price: 650, originalPrice: null,
    badge: 'CONSOLE', inStock: true, rating: 4.8, reviews: 10,
    image: '/images/xbox-series-x.jpg',
    description: 'The fastest, most powerful Xbox ever. Enjoy thousands of games across four generations with 12 teraflops of raw graphic processing power.',
    features: ['Custom AMD Zen 2 processor', '1TB Custom SSD', '12 Teraflops GPU', '4K / 120Hz support', 'Quick Resume', 'Backward compatible'],
  },

  // ─── MONITORS ───
  {
    id: 22, name: 'Sceptre 24" Monitor', category: 'Gaming',
    slug: 'sceptre-24-monitor',
    processor: 'N/A', storage: 'N/A',
    display: '24" HD', price: 155, originalPrice: 170,
    badge: 'NEW', inStock: true, rating: 4.4, reviews: 8,
    image: '/images/sceptre-24-monitor.jpg',
    description: 'Brand new 24 inch monitor. Perfect for work and play with crisp visuals and slim bezel design.',
    features: ['24" Display', 'Brand New', 'HD Resolution', 'Slim Bezel Design', 'VESA Mount Compatible'],
  },

  // ─── VALUE LAPTOPS ───
  {
    id: 9, name: 'HP 820 Elitebook G3', category: 'Laptops',
    slug: 'hp-820-elitebook-g3',
    processor: 'Core i5 6th Gen', storage: '256GB SSD',
    display: '12.5" HD', price: 180, originalPrice: 190,
    badge: 'DEAL', inStock: true, rating: 4.2, reviews: 5,
    image: '/images/hp-820-elitebook-g3.jpg',
    description: 'Compact and powerful HP Elitebook 820 G3. Perfect for professionals on the go.',
    features: ['Core i5 6th Generation', '8GB RAM', '256GB SSD', '12.5" HD Display', 'Windows 11 Pro', 'Lightweight design'],
  },
  {
    id: 10, name: 'HP Pavilion Gaming Laptop', category: 'Laptops',
    slug: 'hp-pavilion-gaming',
    processor: 'AMD Ryzen 5 4600', storage: '512GB SSD',
    display: '15.6" HD', price: 590, originalPrice: 650,
    badge: 'GAMING', inStock: true, rating: 4.5, reviews: 7,
    image: '/images/hp-pavilion-gaming.jpg',
    description: 'HP Pavilion Gaming laptop with AMD Ryzen 5 4600, dedicated NVIDIA GTX 1060 4GB graphics, 16GB RAM, and 512GB SSD.',
    features: ['AMD Ryzen 5 4600', '16GB RAM', '512GB SSD', 'NVIDIA GTX 1060 4GB Dedicated', '15.6" HD Display', 'Gaming keyboard'],
  },
  {
    id: 11, name: 'Dell Latitude E5470', category: 'Laptops',
    slug: 'dell-latitude-e5470',
    processor: 'Core i5 6th Gen', storage: '256GB SSD',
    display: '14" HD', price: 200, originalPrice: 220,
    badge: 'DEAL', inStock: true, rating: 4.3, reviews: 6,
    image: '/images/dell-latitude-e5470.jpg',
    description: 'Reliable Dell Latitude E5470 with Core i5 6th Gen, 256GB SSD, 8GB RAM, backlit keyboard, and excellent battery life. Comes with warranty.',
    features: ['Core i5 6th Generation', '8GB RAM', '256GB SSD', '14" HD Display', 'Backlit Keyboard', 'Excellent Battery', 'With Warranty'],
  },
  {
    id: 12, name: 'HP Elitebook 840 G3', category: 'Laptops',
    slug: 'hp-elitebook-840-g3',
    processor: 'Core i5 6th Gen', storage: '256GB SSD',
    display: '14" HD', price: 200, originalPrice: 240,
    badge: 'DEAL', inStock: true, rating: 4.3, reviews: 8,
    image: '/images/hp-elitebook-840-g3.jpg',
    description: 'Premium HP Elitebook 840 G3 with Core i5 6th Gen, 256GB SSD, 8GB RAM, and backlit keyboard. Wholesale $200, Retail $240.',
    features: ['Core i5 6th Generation', '8GB RAM', '256GB SSD', '14" HD Display', 'Backlit Keyboard', 'Windows 11 Pro'],
  },
  {
    id: 13, name: 'HP 840 Elitebook G6 Core i7', category: 'Laptops',
    slug: 'hp-840-elitebook-g6',
    processor: 'Core i7 7th Gen', storage: '256GB SSD',
    display: '14" HD', price: 330, originalPrice: 380,
    badge: 'DEAL', inStock: true, rating: 4.4, reviews: 4,
    image: '/images/hp-840-elitebook-g6.jpg',
    description: 'High-performance HP Elitebook 840 G6 with Core i7 7th Gen processor, 256GB SSD, 8GB RAM, and backlit keyboard.',
    features: ['Core i7 7th Generation', '8GB RAM', '256GB SSD', '14" HD Display', 'Backlit Keyboard', 'Windows 11 Pro'],
  },
  {
    id: 14, name: 'Dell Latitude 5450', category: 'Laptops',
    slug: 'dell-latitude-5450',
    processor: 'Core i5 5th Gen', storage: '500GB HDD',
    display: '14" HD', price: 160, originalPrice: 180,
    badge: 'DEAL', inStock: true, rating: 4.1, reviews: 5,
    image: '/images/dell-latitude-5450.jpg',
    description: 'Budget-friendly Dell Latitude 5450 with Core i5 5th Gen, 500GB HDD, 8GB RAM, backlit keyboard, and excellent battery life.',
    features: ['Core i5 5th Generation', '8GB RAM', '500GB HDD', '14" HD Display', 'Backlit Keyboard', 'Excellent Battery'],
  },
  {
    id: 15, name: 'Dell Latitude 5470', category: 'Laptops',
    slug: 'dell-latitude-5470',
    processor: 'Core i5 6th Gen', storage: '256GB SSD',
    display: '14" HD', price: 190, originalPrice: 220,
    badge: 'DEAL', inStock: true, rating: 4.3, reviews: 6,
    image: '/images/dell-latitude-5470.jpg',
    description: 'Dell Latitude 5470 with Core i5 6th Gen, 256GB SSD, 8GB RAM, 14" HD display, backlit keyboard, and excellent battery life.',
    features: ['Core i5 6th Generation', '8GB RAM', '256GB SSD', '14" HD Display', 'Backlit Keyboard', 'Excellent Battery'],
  },
  {
    id: 16, name: 'HP Elitebook 840 G5', category: 'Laptops',
    slug: 'hp-elitebook-840-g5',
    processor: 'Core i5 8th Gen', storage: '256GB SSD',
    display: '14" HD', price: 280, originalPrice: null,
    badge: 'DEAL', inStock: true, rating: 4.4, reviews: 5,
    image: '/images/hp-elitebook-840-g5.jpg',
    description: 'HP Elitebook 840 G5 with Core i5 8th Gen processor, 256GB SSD, and 8GB RAM. Premium business laptop in excellent condition.',
    features: ['Core i5 8th Generation', '8GB RAM', '256GB SSD', '14" HD Display', 'Backlit Keyboard', 'Windows 11 Pro'],
  },
  {
    id: 17, name: 'HP Elitebook 1030 G2 x360', category: 'Laptops',
    slug: 'hp-elitebook-1030-g2',
    processor: 'Core i5 7300U 7th Gen', storage: '256GB SSD',
    display: '13.3" FHD Touch', price: 350, originalPrice: 390,
    badge: 'DEAL', inStock: true, rating: 4.5, reviews: 4,
    image: '/images/hp-elitebook-1030-g2.jpg',
    description: 'HP EliteBook 1030 G2 x360 convertible. Core i5 7300U, 8GB DDR4, 256GB M.2 SSD, 13.3" FHD touch screen, 360° hinge, backlit keyboard, fingerprint reader, Windows 10 Pro with Office.',
    features: ['Core i5 7300U 2.6GHz 7th Gen', '8GB DDR4 RAM (Customizable)', '256GB M.2 SSD (Customizable)', '13.3" LED FHD Touch Display', '360° Convertible', 'Backlit Keyboard', 'Fingerprint Reader', 'Windows 10 Pro + Office'],
  },
  {
    id: 18, name: 'Dell Latitude 5420', category: 'Laptops',
    slug: 'dell-latitude-5420',
    processor: 'Core i5 10th Gen', storage: '256GB SSD',
    display: '14" HD', price: 320, originalPrice: null,
    badge: 'DEAL', inStock: true, rating: 4.5, reviews: 3,
    image: '/images/dell-latitude-5420.jpg',
    description: 'Dell Latitude 5420 with Core i5 10th Generation, 256GB SSD, and 8GB RAM. Business-ready laptop with excellent performance.',
    features: ['Core i5 10th Generation', '8GB RAM', '256GB SSD', '14" HD Display', 'Windows 11 Pro', 'Business-grade build'],
  },
  {
    id: 23, name: 'MacBook', category: 'Laptops',
    slug: 'macbook',
    processor: 'Intel Core i5', storage: '256GB SSD',
    display: '13.3" Retina', price: 500, originalPrice: null,
    badge: null, inStock: true, rating: 4.4, reviews: 6,
    image: '/images/macbook.jpg',
    description: 'Apple MacBook in excellent condition. Perfect for everyday use with Retina display and premium build quality.',
    features: ['Intel Core i5', '8GB RAM', '256GB SSD', '13.3" Retina Display', 'macOS', 'Premium aluminum body'],
  },
  {
    id: 24, name: 'Proline Notebook', category: 'Laptops',
    slug: 'proline',
    processor: 'DualCore', storage: '500GB HDD',
    display: '14" HD', price: 110, originalPrice: null,
    badge: 'BUDGET', inStock: true, rating: 4.0, reviews: 4,
    image: '/images/proline.jpg',
    description: 'Affordable Proline notebook with DualCore processor, 500GB storage, 4GB RAM, 14" screen, and excellent battery life.',
    features: ['DualCore Processor', '4GB RAM', '500GB HDD', '14" HD Screen', 'Excellent Battery Life', 'Budget-friendly'],
  },
  {
    id: 25, name: 'HP Spectre 13.5', category: 'Laptops',
    slug: 'hp-spectre',
    processor: 'Core i7 13th Gen', storage: '512GB SSD',
    display: '13.5" OLED', price: 1800, originalPrice: null,
    badge: 'FLAGSHIP', inStock: true, rating: 4.8, reviews: 2,
    image: '/images/hp-spectre.jpg',
    description: 'Brand new boxed HP Spectre 13.5 with Core i7 13th Gen, 512GB SSD, and 16GB RAM. Premium ultrabook with stunning OLED display.',
    features: ['Core i7 13th Generation', '16GB RAM', '512GB SSD', '13.5" OLED Display', 'Brand New Boxed', 'Premium Design'],
  },

  // ─── ACCESSORIES ───
  {
    id: 26, name: 'HP Printer 2320', category: 'Accessories',
    slug: 'hp-printer-2320',
    processor: 'N/A', storage: 'N/A',
    display: 'N/A', price: 55, originalPrice: 70,
    badge: 'DEAL', inStock: true, rating: 4.2, reviews: 5,
    image: '/images/hp-printer-2320.jpg',
    description: 'HP Printer 2320. Reliable printing for home or office use. Available now.',
    features: ['Print, Scan, Copy', 'Wireless connectivity', 'HP quality', 'Affordable printing', 'Available now'],
  },
  {
    id: 27, name: 'Laptop Keyboard Replacement', category: 'Accessories',
    slug: 'laptop-keyboard',
    processor: 'N/A', storage: 'N/A',
    display: 'N/A', price: 20, originalPrice: null,
    badge: 'SERVICE', inStock: true, rating: 4.3, reviews: 10,
    image: '/images/laptop-keyboard.jpg',
    description: 'Laptop keyboard replacement service. From $20. Covers most laptop models.',
    features: ['All major laptop models', 'Quality replacement keys', 'Professional installation', 'Quick turnaround', 'From $20'],
  },
  {
    id: 28, name: 'Laptop Chargers All Types', category: 'Accessories',
    slug: 'laptop-chargers',
    processor: 'N/A', storage: 'N/A',
    display: 'N/A', price: 15, originalPrice: 20,
    badge: 'SERVICE', inStock: true, rating: 4.4, reviews: 15,
    image: '/images/laptop-chargers.jpg',
    description: 'Laptop chargers for all types. Power pack $10, Complete charger $15. All major brands supported.',
    features: ['All laptop brands supported', 'Power pack from $10', 'Complete charger $15', 'Original quality', 'Tested before sale'],
  },

  // ─── BRANDNEW BOXED HP LAPTOPS ───
  {
    id: 29, name: 'HP 250 G9 DualCore', category: 'Laptops',
    slug: 'hp-250-g9',
    processor: 'DualCore', storage: '256GB SSD',
    display: '15.6" HD', price: 290, originalPrice: null,
    badge: 'NEW', inStock: true, rating: 4.3, reviews: 4,
    description: 'Brand new boxed HP 250 G9. DualCore processor, 256GB storage, 4GB RAM. Full warranty included. Delivery available.',
    features: ['Brand New Boxed', 'DualCore Processor', '256GB Storage', '4GB RAM', '15.6" HD Display', 'Full Warranty', 'Delivery Available'],
  },
  {
    id: 30, name: 'HP 15s Core i5 12th Gen', category: 'Laptops',
    slug: 'hp-15s-core-i5-12th',
    processor: 'Core i5 12th Gen', storage: '512GB SSD',
    display: '15.6" HD', price: 560, originalPrice: null,
    badge: 'NEW', inStock: true, rating: 4.6, reviews: 3,
    description: 'Brand new boxed HP 15s with Core i5 12th Gen, 512GB SSD, and 8GB RAM. Full warranty and delivery available.',
    features: ['Brand New Boxed', 'Core i5 12th Generation', '512GB SSD', '8GB RAM', '15.6" HD Display', 'Full Warranty'],
  },
  {
    id: 31, name: 'HP Pavilion 15 Core i5 12th Gen', category: 'Laptops',
    slug: 'hp-pavilion-15-i5-12th',
    processor: 'Core i5 12th Gen', storage: '512GB SSD',
    display: '15.6" HD', price: 875, originalPrice: null,
    badge: 'NEW', inStock: true, rating: 4.7, reviews: 2,
    description: 'Brand new HP Pavilion 15 with Core i5 12th Gen, 512GB SSD, and 8GB RAM. Premium entertainment laptop.',
    features: ['Brand New Boxed', 'Core i5 12th Generation', '512GB SSD', '8GB RAM', '15.6" HD Display', 'Full Warranty'],
  },
];

export function getProductBySlug(slug) {
  return products.find(p => p.slug === slug) || null;
}

export function getProductsByCategory(category) {
  return products.filter(p => p.category.toLowerCase() === category.toLowerCase());
}

export const categories = [
  { slug: 'laptops', name: 'Laptops', icon: 'Monitor', count: 18, desc: 'Professional computing power' },
  { slug: 'gaming', name: 'Gaming', icon: 'Gamepad2', count: 5, desc: 'Consoles, desktops & monitors' },
  { slug: 'accessories', name: 'Accessories', icon: 'Package', count: 3, desc: 'Printers, chargers & repairs' },
];
